import '../experience-v2/prepare-entry.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createGame} from '../experience-v2/slice-game.mjs';
import {createGame as originalGame} from '../src/game.mjs';
import {createSlice,createDirector,SCENARIOS,optionsFrom} from '../experience-v2/director.mjs';
import {courtModel,ROSTER,courtShell} from '../experience-v2/court.mjs';
const config=name=>({...SCENARIOS[name],fixture:SCENARIOS[name].fixture==='defence'?'v2_defence':SCENARIOS[name].fixture});
function run(name='primary',policy=()=>0){const s=createSlice({qa:true,scenario:name}),frames=[];for(let i=0;i<150;i++){const v=s.view();frames.push(v);if(v.stage==='end')return {s,frames};v.decision?s.choose(policy(v)):s.advance();}throw Error('Slice did not finish '+name);}
test('v2 adds only bounded slice entries; every certified handler stays identical',()=>{const copy=fs.readFileSync(new URL('../experience-v2/slice-game.mjs',import.meta.url),'utf8').replace(/    if\(mode==='v2_defence'\|\|mode==='v2_three'\)\{[\s\S]*?\n    \}\n/,'').replace("from '../src/engine.mjs'","from './engine.mjs'").replace("from '../src/content.mjs'","from './content.mjs'");assert.equal(copy,fs.readFileSync(new URL('../src/game.mjs',import.meta.url),'utf8'));});
test('v2 entry leaves original full game and fixture contracts untouched',()=>{for(const fixture of [null,'defence','normal','defthree']){const a=createGame({fixture}),b=originalGame({fixture});for(let i=0;i<40&&a.view().choices.length;i++){assert.deepEqual(a.view(),b.view());a.act(0);b.act(0);}assert.deepEqual(a.trace(),b.trace());}});
test('primary extended slice reaches real off-ball, handling and shooting choices',()=>{const {s,frames}=run();assert.deepEqual(frames.map(f=>f.stage),['arrival','defence','pressure','intent','flight','miss','rebound','contest','secured','transition','offence','offmove','ballhand','drive','shoot','flight','made','end']);assert.deepEqual(s.state().score,{Magic:2,Falcons:0});assert.equal(s.state().decisions,6);});
test('all 27 tactical combinations retain exact direct production traces through offence',()=>{for(let d=0;d<3;d++)for(let sh=0;sh<3;sh++)for(let r=0;r<3;r++){const a=createSlice({qa:true}),b=createGame(config('primary'));let queued=null;for(let i=0;i<150;i++){const v=a.view();if(v.stage==='end')break;if(v.decision){queued=v.stage==='defence'?d:v.stage==='intent'?sh:v.stage==='rebound'?r:0;a.choose(queued);}else{const old=a.view().source.revision;a.advance();if(a.view().source.revision!==old){b.act(queued??0);queued=null;}}assert.deepEqual(a.trace(),b.trace());assert.deepEqual(a.state(),b.state());}assert.equal(a.view().stage,'end');}});
for(const name of Object.keys(SCENARIOS))test('v2 real scenario completes: '+name,()=>{const {s}=run(name);assert.equal(s.view().stage,'end');assert.ok(s.state().decisions>0);});
test('ordinary randomness remains live across 200 seeds and every decision index',()=>{const outcomes=new Set();for(let seed=1;seed<=200;seed++){const a=createSlice({},seed*12345);for(let i=0;i<200;i++){const v=a.view();if(v.stage==='end')break;v.decision?a.choose(seed%v.choices.length):a.advance();}assert.equal(a.view().stage,'end');a.trace().filter(e=>e.type==='SHOT_OUTCOME').forEach(e=>outcomes.add(e.physicalOutcome));}assert.deepEqual([...outcomes].sort(),['blocked','foul','made','miss']);});
test('only meaningful decisions expose controls; automatic beats do not accept player taps',()=>{for(const v of run().frames){assert.equal(v.choices.length>0,v.decision);assert.equal(v.delay===null,v.decision||v.stage==='end');assert.ok(v.choices.every(c=>!/^watch|^continue|^next|^follow|^see where/i.test(c)));}const s=createSlice({qa:true});assert.throws(()=>s.choose(0));s.advance();assert.throws(()=>s.advance());});
test('no shot/rebound outcome is resolved before the corresponding decision and action beat',()=>{const s=createSlice({qa:true});while(s.view().stage!=='intent'){s.view().decision?s.choose(0):s.advance();}assert.equal(s.trace().some(e=>e.type==='SHOT_OUTCOME'),false);s.choose(0);assert.equal(s.trace().some(e=>e.type==='SHOT_OUTCOME'),false);s.advance();s.advance();assert.equal(s.view().stage,'rebound');assert.equal(s.trace().some(e=>e.type==='REBOUND_OUTCOME'),false);s.choose(0);assert.equal(s.trace().some(e=>e.type==='REBOUND_OUTCOME'),false);s.advance();assert.equal(s.trace().findLast(e=>e.type==='REBOUND_OUTCOME').winner,'you');});
test('queued decisions reject double taps without duplicate production decisions',()=>{const s=createSlice({qa:true});s.advance();const v=s.view();s.choose(0,v.revision);assert.throws(()=>s.choose(0,v.revision));const before=s.trace();assert.throws(()=>s.advance(v.revision));assert.deepEqual(s.trace(),before);});
test('ten stable identities, Charlotte 10, Casey 9 and exactly one ball',()=>{assert.equal(ROSTER.length,10);assert.equal(new Set(ROSTER.map(p=>p.id)).size,10);assert.equal(ROSTER.find(p=>p.id==='C').number,10);assert.equal(ROSTER.find(p=>p.id==='F1').number,9);assert.equal((courtShell().match(/data-ball="one"/g)||[]).length,1);assert.equal((courtShell().match(/data-player=/g)||[]).length,10);});
test('court ball is unowned in flight and loose-ball decisions; scores and time are production state',()=>{const s=createSlice({qa:true});for(let i=0;i<100;i++){const v=s.view(),c=courtModel(v,s.trace());assert.deepEqual(c.score,s.state().score);assert.equal(c.clock,s.state().clock);assert.equal(c.players.filter(p=>p.ownsBall).length,c.ball.owner?1:0);if(['flight','miss','rebound','contest'].includes(v.stage)){assert.equal(c.ball.owner,null);assert.equal(c.possession,null);}if(v.stage==='end')break;v.decision?s.choose(0):s.advance();}});
test('defender is between Casey and basket; a three originates outside the actual arc',()=>{for(const name of ['primary','three']){const s=createSlice({qa:true,scenario:name});while(s.view().stage!=='intent')s.view().decision?s.choose(0):s.advance();const c=courtModel(s.view(),s.trace()),f=c.players.find(p=>p.id==='F1'),charlotte=c.players.find(p=>p.id==='C');assert.ok(f.x<charlotte.x&&charlotte.x<940);if(name==='three')assert.ok(Math.hypot(f.x-940,f.y-280)>225);}});
test('rebound transitions only after engine ownership changes, Magic attacks opposite basket',()=>{const s=createSlice({qa:true});while(s.view().stage!=='transition')s.view().decision?s.choose(0):s.advance();assert.equal(s.state().nextTeam,'Magic');const c=courtModel(s.view(),s.trace());assert.equal(c.direction,'left');assert.equal(c.possession,'Magic');});
test('mixed consequence is earned by actual made shot and good contest',()=>{const {frames,s}=run('mixed');const moment=frames.find(v=>v.art==='contest');assert.ok(moment);assert.match(moment.heading,/Great defence.*Casey makes/);assert.equal(moment.source.state.score.Falcons,2);assert.equal(s.trace().find(e=>e.type==='SHOT_OUTCOME').physicalOutcome,'made');assert.ok(run().frames.some(v=>v.art==='rebound'));});
test('QA options are opt-in; developer controls absent from ordinary player mode',()=>{assert.deepEqual(optionsFrom('?scenario=primary'),{qa:false,clean:true,scenario:null});assert.equal(optionsFrom('?qa=1&player=1').clean,true);const ui=fs.readFileSync(new URL('../experience-v2/ui.mjs',import.meta.url),'utf8');assert.match(ui,/if\(options.qa&&!options.clean\)/);assert.doesNotMatch(ui,/\+10|XP|Watch the play/);});
test('completed free throws never leave a player holding the result ball',()=>{const s=createSlice({qa:true,scenario:'foul'});let results=0;for(let i=0;i<100;i++){const v=s.view(),c=courtModel(v,s.trace());if(v.stage==='ft-result'){results++;assert.equal(c.ball.owner,null);assert.ok(c.players.every(p=>!p.ownsBall));}if(v.stage==='end')break;v.decision?s.choose(0):s.advance();}assert.equal(results,2);});
test('closeup rebound includes the same nearby opponent identities as the court',()=>{const s=createSlice({qa:true});while(s.view().stage!=='secured')s.view().decision?s.choose(0):s.advance();const c=courtModel(s.view(),s.trace()),charlotte=c.players.find(p=>p.id==='C');for(const id of ['F1','F5']){const p=c.players.find(p=>p.id===id);assert.ok(Math.hypot(p.x-charlotte.x,p.y-charlotte.y)<200);}assert.equal(s.view().art,'rebound');});

for(const scenario of ['primary','mixed'])test('5v5 identities and visible spacing throughout '+scenario,()=>{
  const s=createSlice({qa:true,scenario}),stages=new Set(),directions=new Set(),teams=new Set();
  const identities=ROSTER.map(({id,name,number,team})=>({id,name,number,team}));
  const shell=courtShell();
  assert.equal((shell.match(/data-team="Magic"/g)||[]).length,5);
  assert.equal((shell.match(/data-team="Falcons"/g)||[]).length,5);
  assert.equal((shell.match(/data-ball="one"/g)||[]).length,1);
  for(let i=0;i<150;i++){
    const v=s.view(),c=courtModel(v,s.trace());stages.add(v.stage);directions.add(c.direction);if(c.possession)teams.add(c.possession);
    assert.equal(c.players.length,10,v.stage);assert.equal(new Set(c.players.map(p=>p.id)).size,10,v.stage);
    assert.deepEqual(c.players.map(({id,name,number,team})=>({id,name,number,team})),identities,v.stage);
    for(const team of ['Magic','Falcons'])assert.equal(c.players.filter(p=>p.team===team).length,5,v.stage);
    assert.equal(c.players.filter(p=>p.name==='Charlotte'&&p.id==='C'&&p.team==='Magic'&&p.number===10).length,1);
    for(const p of c.players){assert.ok(p.x>=50&&p.x<=950&&p.y>=50&&p.y<=510,v.stage+' in-bounds '+p.id);}
    for(let a=0;a<10;a++)for(let b=a+1;b<10;b++){const p=c.players[a],q=c.players[b];assert.ok(Math.hypot(p.x-q.x,p.y-q.y)>=44,v.stage+' overlapping discs '+p.id+'/'+q.id);}
    assert.equal(c.players.filter(p=>p.ownsBall).length,c.ball.owner?1:0);
    if(v.stage==='end')break;v.decision?s.choose(0):s.advance();
  }
  for(const stage of ['defence','flight','transition','offence','ballhand','drive','shoot','end'])assert.ok(stages.has(stage),stage);
  assert.deepEqual([...directions].sort(),['left','right']);assert.deepEqual([...teams].sort(),['Falcons','Magic']);
});
